### ISSUE TITLE
PreviewSceneChanged no triggered ?

### ISSUE THREAD

**Issue by illusdidi** [haganbmj/obs-websocket-js#97] opened 2018-01-23 17:12 UTC
### Description:
Hi,
I don't know if the problem comes from the new update of OBS or obs-websocket-js, or me, but the event PreviewSceneChanged is no longer triggered when the preview scene is changed in Studio Mode. However it seems to be triggered when the current live scene is changed.

### Versions Used (if applicable):
  - obs-websocket-js version: v1.1.0 (2018-01-18 15:53:45+00:00)
  - obs-websocket plugin version: 4.3.1
  - obs-studio version: 21.0.1
  - node version:

**Comment by spesvictus** [comment] 2018-01-23 18:55
I checked. Plugin is emitting the PreviewSceneChanged. The problem is within library. 
Below is output of websocket connection. 
`{
    "scene-name": "Scene Name",
    "sources": [],
    "update-type": "PreviewSceneChanged"
}`

**Comment by illusdidi** [comment] 2018-01-23 20:06
I'm quite lost. When I switch the preview scene on OBS, the event is triggered correctly. But when I do it on my webpage with
`obs.SetPreviewScene({
        'scene-name': nomdescene.value
    })` 
the event is not triggered. Here is a simple version of the webpage where the problem still occurs :
[http://www.chrono-en-ligne.com/webtv/websocket/debug/index.html](url)

**Comment by spesvictus** [comment] 2018-01-23 20:27
Capture the error and post it for contributors to look at.  You could try direct ws connection as well.

**Comment by Lange** [comment] 2019-03-31 19:13
This is confirmed fixed in `obs-websocket` now 🤠

**Closed by Lange** 2019-03-31 19:13 UTC
